vcpkg_download_distfile(ARCHIVE
    URLS "https://github.com/ModOrganizer2/libbsarch/releases/download/${VERSION}/libbsarch.7z"
    FILENAME "libbsarch-${VERSION}.7z"
    SHA512 9F9E6C9C7E2E98E06B265ECC839BC9D452EACD12DC815CB0DC3D38C1E17163BCEFFDE9475204E53DC80FE2E85AA9EA55106F77641160824708C48CD5C52554B6
)
vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE ${ARCHIVE}
    NO_REMOVE_ONE_LEVEL
)

file(INSTALL ${SOURCE_PATH}/include DESTINATION ${CURRENT_PACKAGES_DIR})
file(INSTALL ${SOURCE_PATH}/bin DESTINATION ${CURRENT_PACKAGES_DIR})
file(INSTALL ${SOURCE_PATH}/lib DESTINATION ${CURRENT_PACKAGES_DIR})

file(INSTALL ${SOURCE_PATH}/bin DESTINATION ${CURRENT_PACKAGES_DIR}/debug)
file(INSTALL ${SOURCE_PATH}/lib DESTINATION ${CURRENT_PACKAGES_DIR}/debug)

vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/${PORT}")
